### ISSUE TITLE
fix MSW warning received under CircleCI test

### ISSUE THREAD

**Issue by KevinTriplett** [Hylozoic/hylo-evo#1684]
I'm getting this error with CircleCi consistently:

[MSW] Error: captured a request without a matching request handler:
      
        • GET http://localhost/socket.io/

**Comment by tibetsprague** [comment]
Yes something changed with CircleCI and we need to adjust our setup to work with sockets differently. I have not been able to look into it yet

**Comment by tibetsprague** [comment]
p.s. I would recommend adding new issues to the Hylo Dev project to make sure we track them

**Comment by KevinTriplett** [comment]
I found this in [the CircleCi documents](https://circleci.com/docs/security/):

Web sockets CircleCI uses [Pusher](https://pusher.com/) client libraries for WebSocket communication between the server and the browser, though for installs an internal server called slanger is used, so Pusher servers have no access to your instance of CircleCI, nor your source control system. This is how CircleCI updates the builds list dynamically, or shows the output of a build line-by-line as it occurs. CircleCI sends build statuses and lines of your build output through the web socket server (which unless you have configured your installation to run without SSL, is done using the same certs over SSL), so it is encrypted in transit.

**Comment by tibetsprague** [comment]
this is one we are seeing a lot: 
 console.error
      [MSW] Error: captured a request without a matching request handler:
      
        • GET http://localhost/socket.io/
      
      If you still wish to intercept this unhandled request, please create a request handler for it.
      Read more: https://mswjs.io/docs/getting-started/mocks

      at Object.error (node_modules/msw/node/lib/index.js:3168:13)
      at onUnhandledRequest (node_modules/msw/node/lib/index.js:7822:22)
      at node_modules/msw/node/lib/index.js:7858:13
      at fulfilled (node_modules/msw/node/lib/index.js:51:58)

**Comment by tibetsprague** [comment]
see if this is helpful: https://stackoverflow.com/questions/68024935/msw-logging-warnings-for-unhandled-supertest-requests

**Comment by tibetsprague** [comment]
or this thread? https://github.com/mswjs/msw/issues/655

**Comment by KevinTriplett** [comment]
Good links -- the puzzling aspect is why CircleCi throws the warning but our dev machines do not. Curious

**Comment by thomasgwatson** [comment]
We have moved to github actions and our playwright setup
